/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "secondary-fixed-dim": "#e8c08d",
        "primary-fixed": "#dae2ff",
        "surface-bright": "#fbf9f4",
        "background": "#fbf9f4",
        "surface-container-highest": "#e4e2dd",
        "surface-container-high": "#eae8e3",
        "on-surface": "#1b1c19",
        "secondary": "#77592f",
        "inverse-surface": "#30312e",
        "tertiary-container": "#361b1c",
        "on-secondary-fixed-variant": "#5d421a",
        "on-secondary": "#ffffff",
        "outline-variant": "#c6c6cd",
        "inverse-primary": "#bec6e3",
        "tertiary": "#1c0607",
        "primary-container": "#1a2238",
        "on-error": "#ffffff",
        "primary": "#040c21",
        "on-background": "#1b1c19",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#2d1415",
        "on-primary-fixed-variant": "#3e465e",
        "error": "#ba1a1a",
        "on-primary-fixed": "#131b30",
        "on-primary-container": "#8189a4",
        "surface-variant": "#e4e2dd",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#ffdad9",
        "on-secondary-container": "#785a30",
        "secondary-fixed": "#ffddb4",
        "surface-tint": "#565e77",
        "inverse-on-surface": "#f2f1ec",
        "on-secondary-fixed": "#291800",
        "on-tertiary-fixed-variant": "#5e3e3f",
        "secondary-container": "#fcd39f",
        "surface-container-low": "#f5f3ee",
        "tertiary-fixed-dim": "#e9bcbb",
        "on-surface-variant": "#45464d",
        "outline": "#76777e",
        "surface-dim": "#dbdad5",
        "surface": "#fbf9f4",
        "surface-container": "#f0eee9",
        "on-tertiary-container": "#a88080",
        "primary-fixed-dim": "#bec6e3",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "container-padding": "40px",
        "unit": "8px",
        "sidebar-width": "280px",
        "gutter": "24px",
        "stack-sm": "12px",
        "stack-md": "24px",
        "stack-lg": "48px"
      },
      "fontFamily": {
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "headline-md": ["Playfair Display", "serif"],
        "display-lg": ["Playfair Display", "serif"],
        "nav-link": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Playfair Display", "serif"],
        "label-caps": ["Inter", "sans-serif"]
      },
      "fontSize": {
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-lg": ["32px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "1.4", "fontWeight": "500"}],
        "display-lg": ["48px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "nav-link": ["15px", {"lineHeight": "1.5", "fontWeight": "500"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-lg-mobile": ["28px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "label-caps": ["12px", {"lineHeight": "1.2", "letterSpacing": "0.1em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
